apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: REPLACE_NAMESPACE
  name: REPLACE_POD_NAME
  labels:
    app: REPLACE_POD_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: REPLACE_POD_NAME
  template:
    metadata:
      labels:
        app: REPLACE_POD_NAME
        role: minion
    spec:
      containers:
      - name: minion
        image: REPLACE_IMAGE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 8002
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            value: "REPLACE_POD_NAME"
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_CLUSTER
            value: "REPLACE_CLUSTER"
          - name: MY_DNS
            value: REPLACE_MY_DNS
          - name: MY_MONGO_URI
            value: "REPLACE_MONGO"
      imagePullSecrets:
      - name: regcred
