apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nextensio-ingressgateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-nextensio-agent
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gw-credential
    hosts:
    - "REPLACE_GW"
  - port:
      number: 80
      name: https-internal
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gw-credential
    hosts:
    - "*"
