apiVersion: v1
kind: Service
metadata:
  namespace: nxt-REPLACE_NAMESPACE
  name: REPLACE_POD_NAME-in
spec:
  selector:
    app: REPLACE_POD_NAME
  ports:
  - port: 80
    name: http2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: nxt-REPLACE_NAMESPACE
  name: REPLACE_POD_NAME-in
spec:
  host: REPLACE_POD_NAME-in
  trafficPolicy:
    outlierDetection:
      consecutiveGatewayErrors: 1
      interval: 2s
      baseEjectionTime: 10s
      maxEjectionPercent: 100
      minHealthPercent: 0
